[workspace]
members = ["investigator_analyst", "investigator_extractor" ,"investigator_register","investigator_panel"] 
resolver = "3"

[workspace.package]
version = "0.0.0"
authors = ["GrauKatze"]
edition = '2024'
